package:
  name: reproject
  version: 0.19.0
  top-level:
    - reproject
source:
  url: https://files.pythonhosted.org/packages/source/r/reproject/reproject-0.19.0.tar.gz
  sha256: ba5d6ac9341258a9e270dc87805f3bd7409253ed73b47ae5fa68903b49c172c9

build:
  script: |
    export CFLAGS="${CFLAGS} -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION"

about:
  home: null
  PyPI: https://pypi.org/project/reproject
  summary: Reproject astronomical images
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
