package:
  name: msgpack
  version: 1.2.2
  top-level:
    - msgpack
source:
  sha256: 9eb0b0e602064527a045ea28c4f174ed69383587e29cebe28947e3b84106eb2a
  url: https://files.pythonhosted.org/packages/source/m/msgpack/msgpack-1.2.2.tar.gz
about:
  home: https://msgpack.org/
  PyPI: https://pypi.org/project/msgpack
  summary: MessagePack serializer
  license: Apache-2.0
