package:
  name: libxslt
  version: 1.1.45
  tag:
    - library
    - static_library
source:
  sha256: 9acfe68419c4d06a45c550321b3212762d92f41465062ca4ea19e632ee5d216e
  url: https://download.gnome.org/sources/libxslt/1.1/libxslt-1.1.45.tar.xz

requirements:
  host:
    - libxml

build:
  type: static_library

  script: |
    emconfigure ./configure \
        CFLAGS="-fPIC" \
        --disable-dependency-tracking \
        --disable-shared \
        --without-python \
        --with-libxml-prefix="${WASM_LIBRARY_DIR}" \
        --without-crypto \
        --prefix=${WASM_LIBRARY_DIR}

    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install
about:
  home: https://gitlab.gnome.org/GNOME/libxslt
  license: MIT
