package:
  name: matplotlib
  version: 3.10.8
  tag:
    - min-scipy-stack
  top-level:
    - pylab
    - mpl_toolkits
    - matplotlib
source:
  url: https://files.pythonhosted.org/packages/source/m/matplotlib/matplotlib-3.10.8.tar.gz
  sha256: 2299372c19d56bcd35cf05a2738308758d32b9eaed2371898d8f5bd33f084aa3
  patches:
    - patches/0001-Disable-timer.patch
    - patches/0002-Hardcode-font-cache-path.patch
    - patches/0003-Pyodide-webagg-backend.patch
    - patches/0004-Fix-32bit-casting.patch

build:
  backend-flags: |
    setup-args=-DrcParams-backend=webagg
    setup-args=-Dsystem-freetype=true
  cflags: |
    -fwasm-exceptions
    -fno-lto
  cxxflags: |
    -fno-lto
    -fwasm-exceptions
  ldflags: |
    -fno-lto
    -lfreetype-legacysjlj
    -fwasm-exceptions
  script: |
    embuilder build freetype-legacysjlj --pic
    # matplotlib locates freetype using pkg-config, so we need to set PKG_CONFIG_PATH to point to the directory containing the .pc file for freetype.
    export PKG_CONFIG_PATH=$(em-config CACHE)/sysroot/lib/pkgconfig
    echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
    export SETUPTOOLS_SCM_PRETEND_VERSION=$PKG_VERSION
  post: |
    rm -rf matplotlib/backends/qt_editor
    # mpl.css, mpl.js and mpl_pyodide.js are used by the patched webagg backend, so do not delete them.
    find matplotlib/backends/web_backend -type f ! -name mpl.css ! -name mpl.js ! -name mpl_pyodide.js -delete
    rm -rf sphinxext
    cp $PKGDIR/extras/fontlist.json matplotlib
    cp $PKGDIR/extras/Humor-Sans-1.0.ttf matplotlib/mpl-data/fonts/ttf/Humor-Sans.ttf

requirements:
  host:
    - numpy
  run:
    - contourpy
    - cycler
    - fonttools
    - kiwisolver
    - numpy
    - packaging
    - Pillow
    - pyparsing
    - python-dateutil
    - pytz

about:
  home: https://matplotlib.org
  PyPI: https://pypi.org/project/matplotlib
  summary: Python plotting package
  license: PSF
