name: pyodide-env
channels:
  - conda-forge
dependencies:
  - python=3.14.0
  - nodejs=20
  - ccache
  - f2c
  # swiglpk has compatibility issue with 4.5 or upper
  - swig<4.5 
  - make
  - cmake<4
  - texinfo
  - autoconf
  - automake
  - libtool
  - wget
  - setuptools
  - gfortran
  - pip
