package:
  name: swiglpk
  version: 5.0.13
  top-level:
    - swiglpk

source:
  sha256: 23050101f01ae1de162a68943e49f139dd586eed327324fece57647ec0c52212
  url: https://files.pythonhosted.org/packages/source/s/swiglpk/swiglpk-5.0.13.tar.gz

build:
  script: |
    export GLPK_HEADER_PATH="${WASM_LIBRARY_DIR}/include/"
    
  ldflags: -L$(WASM_LIBRARY_DIR)/lib

requirements:
  host:
    - libglpk
  executable:
    - swig
about:
  home: https://github.com/opencobra/swiglpk
  PyPI: https://pypi.org/project/swiglpk/
  license: GPL-3.0
