package:
  name: clingo
  version: 5.8.0
  top-level:
    - clingo
source:
  url: https://files.pythonhosted.org/packages/f0/05/1a8a34eea27e73e4c6f7c9d0654b4fd7f509a5fbbb7b3eae7735e5ecd1c2/clingo-5.8.0.tar.gz
  sha256: e557d0ab209bfe185e4ae9dde531ca777be1b72a1a13a5d169926a1f9e4c4480
about:
  home: https://github.com/potassco/clingo
  PyPI: https://pypi.org/project/clingo
  summary: CFFI-based bindings to the clingo solver.
  license: MIT
requirements:
  host:
    - cffi
  run:
    - cffi
build:
  script: |
    # These libs are built when building Pyodide main module, but might not be available when building out-of-tree
    embuilder build libdlmalloc libclang_rt.builtins-legacysjlj libc++-legacyexcept libc++abi-legacyexcept libunwind-legacyexcept --pic
extra:
  recipe-maintainers:
    - peter-gy
