package:
  name: psycopg
  version: 3.3.4
  top-level:
    - psycopg

source:
  url: https://files.pythonhosted.org/packages/5c/e0/7b3dee031daae7743609ce3c746565d4a3ed7c2c186479eb48e34e838c64/psycopg-3.3.4-py3-none-any.whl
  sha256: b6bbc25ccf05c8fad3b061d9db2ef0909a555171b84b07f29458a447253d679a

requirements:
  run:
    - psycopg-c

test:
  imports:
    - psycopg
    - psycopg.pq

about:
  home: https://psycopg.org/
  PyPI: https://pypi.org/project/psycopg
  summary: PostgreSQL database adapter for Python
  license: LGPL-3.0-only
extra:
  recipe-maintainers:
    - ryanking13
