package:
  name: yt
  version: 4.4.2
  top-level:
    - yt
source:
  url: https://files.pythonhosted.org/packages/source/y/yt/yt-4.4.2.tar.gz
  sha256: e0883a89c2543b436c3778f555edf253c71f252f744752dc1688f8524ad03b0b
  patches:
    - patches/skip-openmp.patch
requirements:
  host:
    - numpy
  run:
    - ewah_bool_utils
    - numpy
    - matplotlib
    - sympy
    - setuptools
    - packaging
    - unyt
    - cmyt
    - colorspacious
    - tqdm
    - tomli
    - tomli-w
build:
  # The test module is imported from the top level `__init__.py`
  # so it cannot be unvendored
  unvendor-tests: false
about:
  home: https://github.com/yt-project/yt
  PyPI: https://pypi.org/project/yt
  summary: An analysis and visualization toolkit for volumetric data
  license: BSD-3-Clause
