package:
  name: psycopg-c
  version: 3.3.4
  top-level:
    - psycopg_c

source:
  url: https://files.pythonhosted.org/packages/21/7c/c08364f2eab2913e4068b3b955d963e7a3491986a85429990969525def30/psycopg_c-3.3.4.tar.gz
  sha256: ed8106128b2d04359c185fc9641b4409abfce4d0b6fb1d1ff6800646e27f1a22
  patches:
    - patches/0001-Use-Emscripten-endian-functions.patch

requirements:
  host:
    - libpq

build:
  script: |
    export PATH="${WASM_LIBRARY_DIR}/bin:${PATH}"

about:
  home: https://psycopg.org/
  PyPI: https://pypi.org/project/psycopg-c
  summary: PostgreSQL database adapter for Python C optimisation distribution
  license: LGPL-3.0-only
extra:
  recipe-maintainers:
    - ryanking13
