package:
  name: casadi
  version: 3.7.2
  top-level:
    - casadi
source:
  url: https://files.pythonhosted.org/packages/source/c/casadi/casadi-3.7.2.tar.gz
  sha256: b4d7bd8acdc4180306903ae1c9eddaf41be2a3ae2fa7154c57174ae64acdc60d
requirements:
  run:
    - numpy
build:
  vendor-sharedlib: false # done by the package itself
  exports: whole_archive
  # These libs are built when building Pyodide main module, but might not be available when building out-of-tree
  script: |
    embuilder build libdlmalloc libclang_rt.builtins-legacysjlj libc++-legacyexcept libc++abi-legacyexcept libunwind-legacyexcept --pic

    # Prevent CMake from linking against the system Python, which is 64bit and thus incompatible with our 32bit build.
    export CASADI_SETUP_CMAKE_ARGS="-DPYTHON_INCLUDE_DIR=$PYTHONINCLUDE"
  cflags: |
    -fwasm-exceptions
  cxxflags: |
    -fwasm-exceptions
  ldflags: |
    -fwasm-exceptions
    -Wl,-rpath,$ORIGIN
about:
  home: http://casadi.org
  PyPI: https://pypi.org/project/casadi
  summary: CasADi -- framework for algorithmic differentiation and numeric
    optimization
  license: LGPL-3.0-or-later
extra:
  recipe-maintainers:
    - agriyakhetarpal
