package:
  name: libxml
  version: 2.15.3
  tag:
    - library
    - static_library
source:
  sha256: 78262a6e7ac170d6528ebfe2efccdf220191a5af6a6cd61ea4a9a9a5042c7a07
  url: https://download.gnome.org/sources/libxml2/2.15/libxml2-2.15.3.tar.xz

requirements:
  host:
    - libzlib
    - libiconv

build:
  type: static_library
  script: |
    emconfigure ./configure \
        CFLAGS="-fPIC" \
        --disable-dependency-tracking \
        --disable-shared \
        --without-python \
        --with-iconv="${WASM_LIBRARY_DIR}" \
        --with-zlib="${WASM_LIBRARY_DIR}" \
        --prefix=${WASM_LIBRARY_DIR}
    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install
about:
  home: https://gitlab.gnome.org/GNOME/libxml2
  license: MIT
