package:
  name: mysqlclient
  version: 2.2.8
  top-level:
    - MySQLdb

source:
  url: https://files.pythonhosted.org/packages/eb/b0/9df076488cb2e536d40ce6dbd4273c1f20a386e31ffe6e7cb613902b3c2a/mysqlclient-2.2.8.tar.gz
  sha256: 8ed20c5615a915da451bb308c7d0306648a4fd9a2809ba95c992690006306199

requirements:
  host:
    - libopenssl
    - libmariadb

test:
  imports:
    - MySQLdb
    - MySQLdb._mysql

about:
  home: https://github.com/PyMySQL/mysqlclient
  PyPI: https://pypi.org/project/mysqlclient
  summary: Python interface to MySQL backed by MariaDB Connector/C
  license: GPL-2.0-or-later
extra:
  recipe-maintainers:
    - ryanking13
