package:
  name: duckdb
  version: 1.5.1
  # Prebuilt wheel tagged pyemscripten_2026_0
  _disabled: true
  top-level:
    - duckdb
source:
  url: https://github.com/xlwings/duckdb-pyodide/releases/download/duckdb-v1.5.1-pyodide-314.0.0a1/duckdb-1.5.1-cp314-cp314-pyemscripten_2026_0_wasm32.whl
  sha256: 86cc849c4cc14acc151baa1c587f07a79d5f28efb3e826052a4ee493208a77f4
about:
  home: https://github.com/duckdb/duckdb
  PyPI: https://pypi.org/project/duckdb
  summary: A fast in-process analytical database
  license: MIT
